[build-system]
requires = ["uv_build>=0.11.28,<0.12.0"]
build-backend = "uv_build"

[project]
name = "binaryninja-finder"
version = "0.2.0"
description = "Find and install Binary Ninja's Python API"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.9"

[project.urls]
Issues = "https://github.com/trailofbits/binaryninja-finder/issues"
Source = "https://github.com/trailofbits/binaryninja-finder"

[tool.uv.build-backend]
data = { purelib = "_pth" }
